// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    DialogTest: typeof import('./components/nav/DialogTest.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    MessageTest: typeof import('./components/MessageTest.vue')['default']
    NavTitle: typeof import('./components/nav/NavTitle.vue')['default']
    NavTitle2: typeof import('./components/nav/NavTitle2.vue')['default']
  }
}

export { }
